version: "3.8"
services:
  postgres:
    image: postgres:17-alpine
    container_name: excel-postgres
    restart: unless-stopped
    env_file:
      - ./config.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks: # ðŸ”— Agregar esta secciÃ³n para conectar a la red
      - ExcelDB-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d excelDB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: excelDB-backend
    restart: unless-stopped
    env_file:
      - ./config.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      - ExcelDB-network
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "pip install -r requirements.txt &&
            pip install -r requirements-dev.txt &&
            uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:

networks:
  ExcelDB-network:
    driver: bridge
